### ISSUE TITLE
auth_partner login by FS-Token

### ISSUE THREAD

**Issue by michaelkarrer81** [OpenAT/online#55]
# TODO

- [x] Check the fs_ptoken parameter in every url and login if valid
- [x] Make sure the login created a new cooky and reseted everything just like a regular login
- [x] Create the res.user with correct user rights (public and no portal access)
- [x] Rewrite auth_partner_form to include a Logout Button called "Logout to enter a different Token"
- [ ] Move all res.config "Message overwrites" to the correct addons
- [ ] Rework the german translation
- [x] Make sure the login is shown in website_sale_donate (OPC Pages) for aswidget and there is a logout button also if someone is logged in
